[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "beat_challenge_generator"
version = "0.1.0"
description = "A Python tool to generate random beat challenges"
authors = [{ name = "Your Name", email = "you@example.com" }]
license = { text = "MIT" }
readme = "README.md"

dependencies = [
    "loguru",
    "SQLAlchemy",
    "Flask",
    "Flask-Cors",
    "Flask-Migrate",
    "Flask-SQLAlchemy",
    "click>=8.3.1",
]

[project.optional-dependencies]
mysql = ["PyMySQL"]

[project.scripts]
beat-gen = "beat_challenge_generator.main:main"
ingest = "beat_challenge_generator.ingest:main"
beat-cleanup = "beat_challenge_generator.cleanup:main"
beat-init-db = "beat_challenge_generator.init_db:main"
beat-worker = "beat_challenge_generator.worker:main"

[tool.uv]
package = true

[dependency-groups]
dev = [
    "pytest"
]
