from beat_challenge_generator.config import (
    ALLOW_ASYNC_CHALLENGES,
    ALLOW_RANDOM_CHALLENGES,
    ALLOWED_ORIGINS,
    BEAT_API_KEY,
    DATABASE_URL,
    MAX_CONTENT_LENGTH,
    JOB_RATE_LIMIT_SECONDS,
    MAX_JOBS_PER_RATE_WINDOW,
    SECRET_KEY,
    TRUSTED_HOSTS,
)


class Config:
    DATABASE_URL = DATABASE_URL
    SECRET_KEY = SECRET_KEY
    BEAT_API_KEY = BEAT_API_KEY
    DEBUG = False
    TESTING = False
    ALLOWED_ORIGINS = ALLOWED_ORIGINS
    ALLOW_RANDOM_CHALLENGES = ALLOW_RANDOM_CHALLENGES
    ALLOW_ASYNC_CHALLENGES = ALLOW_ASYNC_CHALLENGES
    JOB_RATE_LIMIT_SECONDS = JOB_RATE_LIMIT_SECONDS
    MAX_JOBS_PER_RATE_WINDOW = MAX_JOBS_PER_RATE_WINDOW
    TRUSTED_HOSTS = TRUSTED_HOSTS or None
    MAX_CONTENT_LENGTH = MAX_CONTENT_LENGTH
